# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 130e4ddecf1e31387b6c463ecd26be74c9f7e41d88ad38ea006d95b2acdcabc099878f3840b14045f172d5155d2cf71fae2ee364a58dca5fcff57cd8b4ddeb89

test:
  secret_key_base: d21d2ecf7652a8f61390defe3b36f84e7420b3f0edff005c1746d9e891d0dd59dcf20f7ab8434816ec35450cf13670360b2ea73f841abe78f015cf9f987a027f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
